### ISSUE TITLE
Move to JuMP-dev

### ISSUE THREAD

**Issue by odow** [jump-dev/Pajarito.jl#439]
We should also update https://github.com/JuliaRegistries/General/blob/9c3cdfc70ca33f6163a9ea4ff8aa3890820fc58e/P/Pajarito/Package.toml#L3

**Comment by chriscoey** [comment]
Thanks, you can go ahead and move it anytime

**Comment by odow** [comment]
Done. Maybe wait for the General PR to be merged before tagging a new release
